### ISSUE TITLE
Global Configuration Proposal

### ISSUE THREAD

**Issue by jreilly-lukava** [TheUnderScorer/nx-semantic-release#10]
# Proposal

## Problem
Currently the only way to set options for a release is in each individual NX project configuration.  The more projects in a repo the more repetition and tedium. 

### Common Options

There are many options which are likely to be identical across projects within the repo, `repositoryURL`, `plugins` and `branches` for example.

### Tokenized Options

Options other than the common options, could become more common with the use Tokens, similar to ${PROJECT_DIR}.  Off-hand, ${PROJECT_NAME} seems good, as then `buildTarget` for example could be set to `dist/apps/${PROJECT_NAME}` globally and should be sufficient for all projects.

This proposal is about solving both these use cases.

## Implementation

For backwards compatibility the options would be merge similarly to how they currently are.  Currently,
```
(workspace | angular).json executor options > defaults
````
Using the global configuration would simply add another configuration in the middle,
```
(workspace | angular).json executor options > global > defaults
```

Options will NOT be deep merged. Meaning that a global `plugins` option would be completely overwritten by a workspace.json `plugins` option.

### Opinionated Choices
- Use [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) for the global configuration.  This is the same tool that semantic-release uses.
- Use `nxrelease` as the module name for cosmiconfig.  Meaning the global options could be placed in:
    - a `nxrelease` property in package.json
    - a `.nxreleaserc` file in JSON or YAML format
    - a `.nxreleaserc.json`, `.nxreleaserc.json`, `.nxreleaserc.json`, `.nxreleaserc.json`, or `.nxreleaserc.json` file
    - a `nxrelease.config.js` or `nxrelease.config.cjs` CommonJS module exporting an object

### Conclusion
- I propose to support a global configuration for nx-semantic-release that still allows for overriding global settings at the individual project level through the executor options.
- Allow for predefined token (`${PROJECT_DIR` and `${PROJECT_NAME}` to start) use in the `changeLogFile`, `tagFormat`, `buildTarget`, `commitMessage`, `packageJsonDir` and `gitAssets` options.

Note: I've already started on this work and I just wanted to make this proposal to open it up for discussion before I went way far down the rabbit hole.  Additionally I can't seem to get the tests to run locally.

**Comment by TheUnderScorer** [comment]
Hey jreilly-lukava,

thanks for the proposal! I definitely like the idea of having some kind of global configuration (wish that nx had some built in support for that...).
I also like the idea with tokens - though we need to make sure that everything is properly documented.

Looking forward to seeing your implementation for it, thanks a lot!

Ps. Regarding running tests, what specific issues do you have and what OS are you using? You can try to run `npm run prepare` if the test workspace was not set up automatically properly.

**Comment by TheUnderScorer** [comment]
If possible, let there be two PRs! 🙂

**Comment by jreilly-lukava** [comment]
I've run into the follow situation:

1. Set `dryRun: true` in the new global options
2. NO `dryRun` set in the workspace.json file

The results is that the `dryRun` option is set to `false`.  Why?  It's set to false, because there are defaults set for some options in the schema.json file, so when option is not found in the workspace.json it sets it to `false`.  This is an issue because we want those workspace.json options to override any global options.  But they aren't set, then it should use the global options.

To resolve this issue, I'm thinking of creating a `default-options.ts` file in the executors/semantic-release directory and moving all of the defaults out of the scheme.json file.  This would allow use to merge our options by doing something like
```
const mergedOptions = { ...defaultOptions, ...cosmicOptions, ...projectOptions }
```
Which should then handle all the options in the preferred order of importance.

Thoughts?

**Comment by TheUnderScorer** [comment]
Makes sense! I guess at this point the defaults in schema.json file are not helpful for us, the `default-options.ts` seems like a good solution.

**Comment by TheUnderScorer** [comment]
The global configuration is released 🎉. Thanks for your contribution jreilly-lukava!

I'm going to close the issue for now, I you think like there is something left regarding it feel free to comment, and I will re-open it.
