### ISSUE TITLE
Enhancing nx-semantic-release to Accurately Detect Changes in Merge Commits for Release Generation

### ISSUE THREAD

**Issue by syonthomas** [TheUnderScorer/nx-semantic-release#102]
## Summary
In workflows that prefer merge commits over squashing, the current implementation of _nx-semantic-release_ fails to recognize changes introduced by these merge commits as impacting packages or dependencies. This can lead to the non-generation of new releases, despite the presence of significant changes. The core issue lies in the tool's reliance on `git show --name-status` to evaluate commit impacts, which does not effectively account for the file changes in merge commits. Consequently, this limitation nudges developers towards adopting squash commits, even when merge commits are the preferred method for integrating changes.

## Reproduction

- Setup _nx-semantic-release_ to release from branch main
- Create a branch _feature/branch_
- Issue commits in this feature branch without following the commit convention (e.g: `wip`, `done`)
- Create a merge request
- Merge the merge request with a merge commit using conventional commits: e.g., : `feat: #1 Support for merge commits`

### Expected Behaviour
A new release is created
### Actual Behaviour
No new release is created

### Details
In the pipeline, _nx-semantic-release_ will claim: 
```bash 
Checking if commit done affects dependencies
✔  Commit "done" affects project or its dependencies
Checking if commit feat: #1 Support for merge commits affects dependencies
❌  Commit "feat: #1 Support for merge commits" does not affect project or its dependencies
```
In the later steps, “done” will be filtered out (because it's not a conventional commit) and no release will be created. 

## Impact
Developers are forced to use squash commits when working with `nx-semantic-release`. 

I am aware the topic of squash- vs. merge request is a big one, but I hope you acknowledge that there are certain scenarios in which merge commits are the preferred choice.

## Assumption
_listAffectedFilesInCommit_ in [packages/nx-semantic-release/src/common/git.ts:106](https://github.com/TheUnderScorer/nx-semantic-release/blob/master/packages/nx-semantic-release/src/common/git.ts#L106) uses `git show --name-status` which does not return any affected files for merge commits, leading to the message `...does not affect project or its dependencies`

## Possible Solution
If my assumption is correct, we would need to change 
```typescript 
const files = await exec(`git show --name-status ${commit.commit.short}`); 
``` 
to 
```typescript 
const files = await exec(`git diff --name-status ${commit.commit.short}^ ${commit.commit.short}`);
```
This, however, does only work for merge commits.
We could check if a commit is a merge commit by using `git log -1 --pretty=format:%P [commitId]`. Merge commits return multiple parents, while regular commits only return one parent.

I have briefly and manually tested this for my repository and found that `git show --name-status [commitID]` does not return any changes for merge commits. `git show --name-status -m  [commitID]` shows the changes from each parent, while `git diff status [commitId]^ [commitId]`, at least in my case, shows the correct changes. 

### Contribution
I am willing to help to solve this issue, but I would prefer to only do so if this problem is acknowledged, and it is confirmed that there was no misunderstanding on my side.

**Comment by TheUnderScorer** [comment]
Hi @syonthomas!

Thanks for reporting this. 
I agree that it makes sense to support both squash and merge commit approaches. TBH I wasn't aware that the merge commits are not correctly handled by this plugin. 

If you are willing to help with this, please do, thank you!

**Comment by TheUnderScorer** [comment]
Not stale
