### ISSUE TITLE
Remove Unused 'git' option

### ISSUE THREAD

**Issue by jreilly-lukava** [TheUnderScorer/nx-semantic-release#11]
This option appears to have been introduced in the initial commit, but I don't see that it was used then or now.

https://github.com/TheUnderScorer/nx-semantic-release/blob/07fceae2dfbbb3c6e9e84284526ab068b9f5d87b/packages/nx-semantic-release/src/executors/semantic-release/semantic-release.ts#L13

**Comment by TheUnderScorer** [comment]
Hm, I think that I've had some ideas for this flag that in the end I've forgotten about 😁. Will take a look into that, thanks!
