### ISSUE TITLE
No cached ProjectGraph is available with nx-semantic-release and NX >v19.3

### ISSUE THREAD

**Issue by NickDub** [TheUnderScorer/nx-semantic-release#111]
Using the “@theunderscorer/nx-semantic-release” plugin, for all NX versions >v19.3, I get this error: 
<img width="644" alt="image" src="https://github.com/user-attachments/assets/6556ddb0-11b7-4a93-ada1-fbf3d57eb02c">

With nx report: 
<img width="308" alt="image" src="https://github.com/user-attachments/assets/06021a2e-be64-44b5-a08f-a8dc58b82a75">

So I can't release with the latest version of NX. 😞 

It seems to be the same problem as described here: https://github.com/TriPSs/nx-extend/issues/294
Can you update the NX version of your plugin to solve this problem?

**Comment by NickDub** [comment]
@TheUnderScorer, any news on this?
When are you going to update the NX version?

Thanks

**Comment by TheUnderScorer** [comment]
Hey @NickDub!

I'll add support for latest NX version soon.
