### ISSUE TITLE
Any way to trigger only one push for mutliple packages changed? 

### ISSUE THREAD

**Issue by airtonix** [TheUnderScorer/nx-semantic-release#27]
if more than one package changes, it currently results in multiple commits **_and pushes_**.

This causes the second push to fail, because it doesn't do a `git pull --no-edit` 

so we'll need to do: 

- `git pull origin master --no-edit`
- somehow defer pushing commits till end? maybe an option "no push" so we can use another github action to push afterwards ?

**Comment by TheUnderScorer** [comment]
Hey @airtonix,

did you try to run the releases in serial rather than in parallel? For example: 
```
npx nx run-many --target=release --all --maxParallel=1
```

**Comment by airtonix** [comment]
@TheUnderScorer Ill give it a go

**Comment by airtonix** [comment]
@TheUnderScorer thanks, seems like this works.
