### ISSUE TITLE
question: why do we need to add the semantic-release entry to workspace.json

### ISSUE THREAD

**Issue by airtonix** [TheUnderScorer/nx-semantic-release#28]
Docs mention that we should add the following to our `workspace.json`.

```json
{
  "$schema": "./node_modules/nx/schemas/workspace-schema.json",
  "version": 2,
  "projects": {
    ...
  },
  "release": {
    "executor": "@theunderscorer/nx-semantic-release:semantic-release"
  }
}
```

and the following to each of our projects that we wish to manage versions and changelogs for to their `project.json`: 

```json
{
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "tags": [],
  "targets": {
    "release": {
      "executor": "@theunderscorer/nx-semantic-release:semantic-release"
    }
  }
}
```

questions: 

1. why do we add it to the `workspace.json`
2. why are we adding it at that level? I can't find documentation on https://nx.dev/ about that.

**Comment by TheUnderScorer** [comment]
Hey @airtonix.

I see that this documentation part could be a bit confusing and use a bit of rewording.

Generally speaking, you only need to add the `@theunderscorer/nx-semantic-release:semantic-release` executor to the project configuration you wish to release. This can be done either in `project.json` file in a particular project, or `projects.your-projects` path in `workspace.json`

Let me know if you have any more questions!

**Comment by airtonix** [comment]
yeah i guess the main question i had was around this : 

```json
{
  "$schema": "./node_modules/nx/schemas/workspace-schema.json",
  "version": 2,
  "projects": {
    ...
  },
  "release": { 👈️ 1️⃣
    "executor": "@theunderscorer/nx-semantic-release:semantic-release"
  }
}
```

1️⃣ what does this do? and where can i read more about so that i might apply it to other plugins/executors/etc?

**Comment by TheUnderScorer** [comment]
Your example is not correct usage. You should add the "executor" to your project configuration, for example like this (in case of **workspace.json**):
```json
{
  "$schema": "./node_modules/nx/schemas/workspace-schema.json",
  "version": 2,
  "projects": {
    "my-project": {
      "projectType": "app",
      "tags": [],
      "targets": {
        "semantic-release": {
          "executor": "@theunderscorer/nx-semantic-release:semantic-release"
        }
      }
    }
  }
}
```

You can read more about executors in NX [here](https://nx.dev/plugin-features/use-task-executors) 😉

**Comment by airtonix** [comment]
ahh ok, i guess i was just copying what you had in one of your projects.

good to know i can remove it.
