### ISSUE TITLE
workspace.json is deprecated

### ISSUE THREAD

**Issue by allbetter-max** [TheUnderScorer/nx-semantic-release#31]
Hi, 

The documentation in the README recommended installation process by using workspace.json, however has been [deprecated](https://nx.dev/deprecated/workspace-json). 

What is the recommended installation instructions for the project?

**Comment by TheUnderScorer** [comment]
Hey @allbetter-max!

It's still the same, however you just have to add it in `project.json` in the project root (e.g: apps/my-app/project.json` as you would do with any other executor:
```json
{
  "name": "my-app",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "projectType": "application",
  "sourceRoot": "apps/my-app/src",
  "targets": {
    "release": {
      "executor": "@theunderscorer/nx-semantic-release:semantic-release"
    }
  },
  "tags": []
}
```

I'll update documentation soon to reflect that.
