### ISSUE TITLE
[Bug] --git cli flag is not a part of schema

### ISSUE THREAD

**Issue by roman-supy-io** [TheUnderScorer/nx-semantic-release#36]
Running `npm run affected:release -- --changelog=false --github=false --git=false` still adds `git` step, since `--git` is not a part of schema and therefore becomes `"false"` (string) instead of `false` (boolean).

**Comment by TheUnderScorer** [comment]
Hey @roman-supy-io!

What is the point of the `git` flag? I don't see it in the `semantic-release` config.
