### ISSUE TITLE
changelog not respecting releaseRules `release: false`

### ISSUE THREAD

**Issue by Cammisuli** [TheUnderScorer/nx-semantic-release#38]
With the semantic-release/commit-analyzer releaseRules options, we can add do this:
```
"releaseRules": [
  {"scope": "no-release", "release": false}
]
```
>https://github.com/semantic-release/commit-analyzer#releaserules

Currently, adding `"release": false` throws a schema exception. 

But even going into node_modules and modifying the schema.json, the scope that was put as `"release": false` still shows up in the change log. 

I would expect that the change log not include these types of commits.

**Comment by TheUnderScorer** [comment]
Hi @Cammisuli!

Thanks for reporting this issue, I'll adjust schema in the upcoming release.

FYI: Setting `release` to `false` won't cause it to not appear in changelog, it simply causes it to not trigger release if it is the only change. To change how changelog is generated, you need to use `preset` along with `presetConfig` properties. You can check release configuration in plugin itself (located in `packages/nx-semantic-release/project.json) for reference. For example:
```
{
              "type": "docs",
              "section": "Documentation",
              "hidden": true
            },
```
will cause to commits like `docs: update docs` to not appear in changelog.

**Comment by Cammisuli** [comment]
Ah, that makes more sense. Thank you!

I'll play around with it 🙂

**Comment by TheUnderScorer** [comment]
You can try to use the [Skipping Commits](https://github.com/TheUnderScorer/nx-semantic-release#skipping-commits) feature. So e.g for vscode commits:

```
feat(vscode): xyz

[only vscode]
```

The footer won't be included in the changelog.
