### ISSUE TITLE
📃 Documentation  & Usage

### ISSUE THREAD

**Issue by tomavic** [TheUnderScorer/nx-semantic-release#56]
I landed here from google search. Thanks for the great effort.

From the first sight I couldn't know where to add the following inside the `project.json`

```ts
{
  "semantic-release": {
    "executor": "@theunderscorer/nx-semantic-release:semantic-release"
  }
}
```

And then after some Search, I found that I should add it to the `options` object.

Here the problem, after all that i tried 

```shell
$ npx nx run nx-angular13:semantic-release                                                                   

> nx run nx-angular13:semantic-release

Cannot find module 'nx/src/generators/utils/project-configuration'
Require stack:
- /Users/hatem/Desktop/hx/node_modules/@theunderscorer/nx-semantic-release/node_modules/@nrwl/devkit/nx-reexports-pre16.js
- /Users/hatem/Desktop/hx/node_modules/@theunderscorer/nx-semantic-release/node_modules/@nrwl/devkit/index.js
- /Users/hatem/Desktop/hx/node_modules/@theunderscorer/nx-semantic-release/src/executors/semantic-release/semantic-release.js
- /Users/hatem/Desktop/hx/node_modules/@theunderscorer/nx-semantic-release/src/executors/semantic-release/executor.js
- /Users/hatem/Desktop/hx/node_modules/nx/src/config/workspaces.js
- /Users/hatem/Desktop/hx/node_modules/nx/src/command-line/run.js
- /Users/hatem/Desktop/hx/node_modules/nx/bin/run-executor.js

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "nx-angular13:semantic-release" failed

   Failed tasks:
   
   - nx-angular13:semantic-release
```

Could you please help

**Comment by TheUnderScorer** [comment]
Hi @tomavic!

Did you try to run `npx nx g @theunderscorer/nx-semantic-release:install` to install the plugin correctly? 

After that you can try to run `npx nx g @theunderscorer/nx-semantic-release:setup-project nx-angular13` to setup the project and see if it will work for you.

**Comment by tomavic** [comment]
I have been trying your plugin and semantic-release-plus

But I could not completely setup any of them as I expected. 

What I want to do is, to have a monorepo for npm packages only (Angular Libraries) and I want to publish each one with different version independently.

Your help is Appreciated

**Comment by TheUnderScorer** [comment]
In that case, please try to run these two commands I sent you in the previous message. They should guide you on how to set up the plugin correctly 😃.

**Comment by tomavic** [comment]
<img width="650" alt="Screenshot 2023-04-13 at 2 56 14 PM" src="https://user-images.githubusercontent.com/17650005/231765463-8d2cf2c8-9d82-462f-8fe3-a692bc474b36.png">

@TheUnderScorer

**Comment by tomavic** [comment]
I am closing this issue after I have used latest of Node.js `v18.x` & Nx `v15.x`

I am trying now to mimic the same configs of semantic release in this project 

https://github.com/tomavic/myreads-tracker-nx-react-semantic/blob/main/.releaserc.json

@TheUnderScorer Appreciate your help if you could create an example repo with same configs.
