### ISSUE TITLE
HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by ryanbas21** [TheUnderScorer/nx-semantic-release#58]
Hi,
i've had this issue on other repos using Semantic Release. It's actually tracked here: https://github.com/semantic-release/semantic-release/issues/2204 

```
HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
```

I've solved this using https://github.com/semantic-release/github/issues/299#issue-742793150 personal fork, but there seems to be a few other solutions within that issue that we could use here in this repo for the time being until this is solved.

**Comment by TheUnderScorer** [comment]
Thanks @ryanbas21. I've created #61 which when resolved, should provide some workaround when using this configuration:
```json
[
  "@semantic-release/github",
  {
    "successComment": false,
    "failTitle": false
  }
]
```
