### ISSUE TITLE
Cannot find file template.hbs

### ISSUE THREAD

**Issue by ryanbas21** [TheUnderScorer/nx-semantic-release#59]
I keep running into an issue where in CI the plugin doesn't find the template.hbs file from conventional changelog writer.

```
    at async next (file:///home/runner/work/forgerock-javascript-sdk/forgerock-javascript-sdk/node_modules/@theunderscorer/nx-semantic-release/node_modules/p-reduce/index.js:15:44) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/work/forgerock-javascript-sdk/forgerock-javascript-sdk/node_modules/conventional-changelog-writer/templates/template.hbs',
  pluginName: '[Function: nx-semantic-release]'
}

 >  NX   ENOENT: no such file or directory, open '/home/runner/work/forgerock-javascript-sdk/forgerock-javascript-sdk/node_modules/conventional-changelog-writer/templates/template.hbs'
 ```
 
 I've tried installing the package itself in CI as well, and i've verified in my local node_modules that this does exist so its odd but i dont think i can get around this without not generating changelog?

**Comment by TheUnderScorer** [comment]
Hey @ryanbas21! 

This problem seems quite tricky to solve without knowing your CI setup. Are you using some kind of cache for your dependencies?

**Comment by ryanbas21** [comment]
Hey - I do not have any caching going on here. I'm running `npm ci` and it just consistently fails. I've had to disable the release note generation.

https://github.com/ForgeRock/forgerock-javascript-sdk/actions/runs/4735344829/jobs/8405485081 and i'e tried to manually install conventional changelog writer as well.

**Comment by TheUnderScorer** [comment]
Hmm, in that case, that's very weird indeed 😁.

Could you try it with the commit preset that is used by the plugin itself: https://github.com/TheUnderScorer/nx-semantic-release/blob/master/packages/nx-semantic-release/project.json#L54 ? For that, you will also need to install `conventional-changelog-conventionalcommits` package. Let me know if that helps!

**Comment by ryanbas21** [comment]
> Hmm, in that case, that's very weird indeed 😁.
> 
> Could you try it with the commit preset that is used by the plugin itself: https://github.com/TheUnderScorer/nx-semantic-release/blob/master/packages/nx-semantic-release/project.json#L54 ? For that, you will also need to install `conventional-changelog-conventionalcommits` package. Let me know if that helps!

I can try it again later, but my first try with this, the CI hung on the release notes step. I will update if I notice anything changes

**Comment by ryanbas21** [comment]
I think this is because iw asn't adding my git config email in ci.
