### ISSUE TITLE
Support for Nx 16

### ISSUE THREAD

**Issue by Cammisuli** [TheUnderScorer/nx-semantic-release#62]
Nx 16 is going to be coming out soon, and currently we're using this plugin for Nx Console. 

One of the biggest changes for Nx 16 is the rescope from `@nrwl` packages to `@nx` packages. 

I'm going to create a PR to help with this migration. Basically for testing and make sure that everything is updated correctly and runs smoothly for others as well (before we go full release 🙂)

**Comment by TheUnderScorer** [comment]
Thanks a lot @Cammisuli!
