### ISSUE TITLE
Can't use to deploy `apps` with Nx

### ISSUE THREAD

**Issue by tomavic** [TheUnderScorer/nx-semantic-release#64]
Hi there, It's me again.

https://github.com/tomavic/enigma-nx-angular

I have managed to setup your plugin with my Monorepo (1 App, 2 Libs)

But the initial setup with Nx, I found that the `App` project does not have a `package.json` file.

Should I create one for the project?

**Comment by TheUnderScorer** [comment]
Hi!

It depends. It is useful if you want to store the app version and use it in some other places, but it is not required :)

**Comment by tomavic** [comment]
Yeah indeed. I added a `package.json` file and added `npm: false`. But I don't know if there is still missing configs.

**Comment by TheUnderScorer** [comment]
It doesn't look like it, `npm: false` is enough if you don't care about publishing the package, or bumping the version in `package.json`
