### ISSUE TITLE
Publish to npm is not workign

### ISSUE THREAD

**Issue by khsn0w** [TheUnderScorer/nx-semantic-release#68]
Hello 👋🏼 

I would like to thank you for providing this library 👏🏼  and any other contributor.

I am using this configuration under my `project.json` in one of the library we built 

```json 
  "semantic-release": {
      "executor": "@theunderscorer/nx-semantic-release:semantic-release",
      "options": {
        "outputPath": "dist/libs/network-bridge"
      }
    },

```

During the CI run I keep getting this line 

`[@semantic-release/npm] › ℹ  Skip publishing to npm registry as npmPublish is false`

After checking the code source of the plugin, I think the reason was due those [lines](https://github.com/TheUnderScorer/nx-semantic-release/blob/master/packages/nx-semantic-release/src/executors/semantic-release/plugins.ts#L22-L43) 

In fact if there is a `package.json` on the library root the `npmPublish` will set to false, is this an intended behaviour of the plugin?

Thanks in advance.

PS: for now I am overriding those values with the `plugins` option but I am wondering if is it the normal behaviour.

**Comment by TheUnderScorer** [comment]
Hi @khsn0w!

This behavior is intended, usually, you want to publish the built library (defined via `outputPath`) to the npm, and not the source files located at the root of the project 😄.

If you are still unable to publish the package to NPM, try to add these fields to `package.json`:

```json
  "private": false,
  "publishConfig": {
    "access": "public",
    "registry": "https://registry.npmjs.org/"
  }
```
