### ISSUE TITLE
Allow specifying presetConfig for @semantic-release/release-notes-generator

### ISSUE THREAD

**Issue by minwork** [TheUnderScorer/nx-semantic-release#69]
Hey,

From what I've saw [in source code](https://github.com/TheUnderScorer/nx-semantic-release/blob/master/packages/nx-semantic-release/src/executors/semantic-release/plugins.ts#L73C35-L73C35) there should be a possibility to pass `presetConfig` to `@semantic-release/release-notes-generator` but it seems it is ignored / overwritten.

Consider `nxrelease.config.js` file as follows

```ts
releaseRules: [
   // ...
    { type: 'build', release: 'patch' },
],
presetConfig: {
    types: [
     // ...
      { type: 'build', section: 'Build config' },
      // ...
    ],
  },
```

I've observed that although "build commit" triggers patch release it does not create "Build config" section in CHANGELOG nor put that "build commit" into the CHANGELOG at all.
After releasing CHANGELOG has just an empty section as shown below. 

```
"new-version" (2023-XX-XX)

"previous-version" (2023-XX-XX)

Bug Fixes
  - Some bug fix commit
  - ...
```

**Comment by TheUnderScorer** [comment]
Hi! 

I think that you also need to change the `preset` to `conventionalcommits` for it to work correctly. At least it's what I had to do with this library to make it work. You can check the release configuration that I use in `packages/nx-semantic-release/project.json`

**Comment by minwork** [comment]
Thanks, that's probably it

**Comment by minwork** [comment]
Hey @TheUnderScorer the method you described is working but only if I set it in `project.json` options and is not working if I use common configuration file `nxrelease.config.js` in repository root directory.

**Comment by TheUnderScorer** [comment]
Are you sure that you configured it correctly in the common configuration file? I don't see any reason why it wouldn't work like this 😄
