### ISSUE TITLE
`preset` configuration option from config file gets overwritten by the executor default property

### ISSUE THREAD

**Issue by andrevechina** [TheUnderScorer/nx-semantic-release#70]
### Description

Even though it is not documented, it seems to be possible to set the `preset` option as the `SemanticReleaseOptions` type even defines the `preset` property.

https://github.com/TheUnderScorer/nx-semantic-release/blob/55df58ca8416acaa61268e82c31c91ff623223fb/packages/nx-semantic-release/src/executors/semantic-release/semantic-release.ts#L23-L46

The `preset` config is being correctly applied and forwarded to `semantic-release` when the configuration is being defined in the `project.json` file:

```
{
  "targets": {
    "semantic-release": {
      "executor": "@theunderscorer/nx-semantic-release:semantic-release",
      "options": {
        "preset": "conventionalcommits"
      }
    }
  }
}
```

Unfortunately is it not possible to set `preset` in the `nxrelease` config file, because that value get overwritten by the executor default property.

```
module.exports = {
    // ...
    preset: 'conventionalcommits', // always overwritten by 'angular'
    presetConfig,
    releaseRules
};
```

### Workaround
Set the `preset` config in all `project.json`s.

**Comment by TheUnderScorer** [comment]
Hi @andrevechina,

thanks, that was a good catch! I also appreciate your PR 😃
