### ISSUE TITLE
Skip publishing  as npmPublish is [secure]

### ISSUE THREAD

**Issue by daniel-clover** [TheUnderScorer/nx-semantic-release#79]
Not sure what the following messaging means:

`[@semantic-release/npm] › ℹ  Skip publishing to npm registry as npmPublish is [secure]`

Does the "[secure]" value indicate something?  
Should this be an error?

Thanks!

**Comment by daniel-clover** [comment]
hey @TheUnderScorer ! 

The problem is that the publishing step is skipped, so the package isn't pushed up to our artifactory.

Any ideas on what I could do? is there any way to force publishing?

Thanks!!!
[log (21).txt](https://github.com/TheUnderScorer/nx-semantic-release/files/12516532/log.21.txt)

**Comment by TheUnderScorer** [comment]
Try to set this in `package.json`:

```json
  "publishConfig": {
    "access": "public",
    "registry": "https://registry.npmjs.org/"
  },
  "private": false
```

**Comment by TheUnderScorer** [comment]
Did you set it in the `package.json` of the project that you are trying to publish?
