### ISSUE TITLE
internal dependencies bumps

### ISSUE THREAD

**Issue by mat813** [TheUnderScorer/nx-semantic-release#80]
I have a monorepo with :

- `packages/common`
- `packages/lib-a`
- `packages/lib-b`
- `packages/lib-c`

`lib-a`, `lib-b` and `lib-c` have a dependency on `common`, and `lib-c` also has a dependency on `lib-a`.

Now, I commit a fix in packages/common, pushes, and nx-semantic-release goes to do its job, and does 4 commits, add 4 tags and publish 4 the packages have new versions.

But the `dependencies` lines in all `lib-*/package.json` (and all their generated packages) still have the old `common` version, and get re-released without any change except their version bump.

I have a feeling that, either I skipped a step, or something is missing somewhere, and those dependencies should somehow auto-update themselves.
In my example, `lib-a` and `lib-b` should have the new `common` version, and `lib-c` should have the new `common` and `lib-a` version automagically updated in their dependencies.
Because, otherwise, why release new versions of those packages.
I mean, if the only reason to release a new `lib-a` is because `common` has a new version, then the new version of `lib-a` should depend on the new version of `common`.

**Comment by TheUnderScorer** [comment]
Hey @mat813,

if everything is configured correctly, the built packages should contain correct dependencies with their respective versions.

To do that, make sure that you've specified `buildTarget` and `outputPath` and run the release via `npx nx run-many --target=<YOUR_RELEASE_TARGET> --all --parallel --maxParallel=1`. This will release your packages in the following order:
- `packages/common`
- `packages/lib-a`
- `packages/lib-b`
- `packages/lib-c`

and in the end, they should have correct dependency versions defined in their built `package.json` files.

Hope that helps.
