### ISSUE TITLE
Add support for single version for all packages

### ISSUE THREAD

**Issue by tukusejssirs** [TheUnderScorer/nx-semantic-release#82]
In `README.md`, I’ve found the following note:

> For now this package supports only Independent versioning mode, synced mode is planned to be added soon.

I presume that by _synced mode_ you mean using a single version for all packages in monorepo. Now, I prefer versioning all apps in a monorepo after each commit I make to any of the packages, as the packages need to match their version when used together.

Therefore, my question is: when is the _synced mode_ planned to be added? Thanks in advance! :pray:

**Comment by TheUnderScorer** [comment]
Sadly, I don't have time for now to implement it 😢. You can check [this](https://github.com/jscutlery/semver) plugin, which supports synced mode.
