### ISSUE TITLE
New projects analyze all previous commits

### ISSUE THREAD

**Issue by jacobtipp** [TheUnderScorer/nx-semantic-release#90]
Just want to say, your library is fantastic, I have been using it for many projects, big and small. Although this is one issue that has been bothering me.

If I add a new project to my Nx monorepo, `semantic-release` will retrieve all previous commits if no git tag or previous release is found. If my new project depends on another project that has a previous release, it will analyze and add any commits of the dependency to the initial release of my new project.

For example, I have a project `bloc` that has many releases. When I added a new project  `bloc-devtools` to my monorepo, it depends on the `bloc` package, this is the log entry during my release workflow for the initial commit of `bloc-devtools`:

```bash
[7:24:15 PM] [semantic-release] › ℹ  No git tag version found on branch main
[7:24:15 PM] [semantic-release] › ℹ  No previous release found, retrieving all commits
[7:24:15 PM] [semantic-release] › ℹ  Found 150 commits since last release
[7:24:15 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "[Function: nx-semantic-release]"
[7:24:15 PM] [semantic-release] [[Function: nx-semantic-release]] › ℹ  Found following dependencies: "bloc" for project "bloc-devtools"
```

A release is created and everything works fine, I have many projects that also depend on `bloc`. The problem lies in the changelogs. For each new project that depends on another project, the first changelog entry always adds every single dependency commit.

For example here is what the first changelog entry looks like for `bloc-devtools`:

Notice the first entry, `v1.0.0` shows all commits for `bloc`.

Here is a link to the [repo](https://github.com/jacobtipp/bloc-state), you will see that most projects in the packages directory depend on bloc, and the changelogs all have this behavior for the first release.

It would be nice if only the inital commit for a new project is shown, and not all of the previous commits for any projects it depends on within the first changelog entry. 

![CHANGELOG.md](https://i.imgur.com/ZK853Ox.png)

**Comment by TheUnderScorer** [comment]
Hey @jacobtipp!

One solution for this would be to create the first tag manually. After that, the next release should include only commits created after this manual release, so in your case, it would only contain the initial commit.

I hope that helps!

**Comment by jacobtipp** [comment]
> Hey @jacobtipp!
> 
> One solution for this would be to create the first tag manually. After that, the next release should include only commits created after this manual release, so in your case, it would only contain the initial commit.
> 
> I hope that helps!

Thanks, this definitely works!
