### ISSUE TITLE
Tag format not being respected?

### ISSUE THREAD

**Issue by polyphilz** [TheUnderScorer/nx-semantic-release#91]
Hey - thanks for this plugin, it's great! This is my `.nxreleaserc.json`:

```
{
  "changelog": true,
  "npm": false,
  "github": true,
  "repositoryUrl": "https://github.com/<repo>",
  "branches": ["main", { "name": "rc-*", "prerelease": true }],
  "tagFormat": "${PROJECT_NAME}-v${version}"
}
```

...but for some reason, the tag that gets created with the prerelease is `${PROJECT_NAME}-v${version}-{branchName}.<some-num>`. I thought if I hardcoded in the `tagFormat` as I did there it wouldn't append anything to it; how do I prevent that?

**Comment by TheUnderScorer** [comment]
Hey @polyphilz!

In [this](https://github.com/TheUnderScorer/nx-semantic-release/issues/92) issue I've provided a reason for why that is happening.
