### ISSUE TITLE
Unknown branch name appended to release tag and tilte

### ISSUE THREAD

**Issue by gavin-traba** [TheUnderScorer/nx-semantic-release#92]
When generating a release, the tag is made as `${PROJECT_NAME}-v${version}-${branchName}` which is not in my configuration.

Current Config:
```
{
  ...
  "branches": ["main", { "name": "rc-*", "channel": "rc", "prerelease": true }],
  "tagFormat": "${PROJECT_NAME}-v${version}"
}
```
![Screenshot 2023-12-07 at 11 56 09 AM](https://github.com/TheUnderScorer/nx-semantic-release/assets/150265844/72ed4ab6-09ff-4067-82e7-f64286ff81f4)

**Comment by TheUnderScorer** [comment]
Hey @gavin-traba!

It's part of semantic-release behavior. The reason here is the `"name": "rc-*"` configuration. Pre-release tags are always suffixed with the `name`, and since it's a wildcard in your case, anything that goes there will be used as part of the tag.
