### ISSUE TITLE
Conditionally load plugin per package ?

### ISSUE THREAD

**Issue by jbsouvestre** [TheUnderScorer/nx-semantic-release#94]
Hey, 

I'm trying to implement semantic release on an NX monorepo that contains both javascript and python packages, this is achieved on the python side using `@nxlv/python` and hopefully `semantic-release-pypi` 

However, it seems that the pypi plugin is picking up the javascript packages.

Is there a way to tell nx-semantic-release to only load the pypi plugin on specific packages (via project tag or something) ?

More generally, is it possible to conditionally load plugins per package ?

Thanks

**Comment by TheUnderScorer** [comment]
Hey @jbsouvestre!

I don't fully understand the issue here. You can use specific `project.json` to provide additional configuration per project, this includes plugins:
```
{
  "name": "nx-semantic-release",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "packages/nx-semantic-release/src",
  "projectType": "library",
  "targets": {
    "semantic-release": {
      "executor": "@theunderscorer/nx-semantic-release:semantic-release",
      "options": {
           "plugins" [...]
        }
      }
    }
  }
}
```

Let me know if that helps!
