### ISSUE TITLE
Honor "dependsOn" configuration for build target

### ISSUE THREAD

**Issue by tet-lenovo** [TheUnderScorer/nx-semantic-release#97]
The build target in my nx configuration is a post processing step that needs to happen after the build is completed.  My configuration looks something like this:
        "build": {
            "executor": "@nx/js:tsc",
            "outputs": ["{options.outputPath}"],
            "options": {
                "outputPath": "dist/libs/blah",
                "main": "libs/blah/src/index.ts",
                "tsConfig": "libs/blah/tsconfig.lib.json",
                "assets": ["libs/blah/*.md"]
            }
        },
        "post-build": {
            "executor": "nx:run-commands",
            "dependsOn": ["build"],
            "options": {
                "cwd": "dist/libs/blah,
                "command": "npm i"
            }
        },
        "semantic-release": {
            "dependsOn": ["lint", "test", "post-build"],
            "executor": "@theunderscorer/nx-semantic-release:semantic-release",
            "options": {
                "github": false,
                "changelog": true,
                "npm": true,
                "tagFormat": "blah-${VERSION}",
                "buildTarget": "blah:build",
                "outputPath": "dist/libs/blah"
            }
        }

If I configure the "buildTarget" for "blah:post-build", nx-semantic-release will only run that target and not the dependent target first.  If I change "buildTarget" to "blah:build", nx-semantic-release runs "build", even though "semantic-release" dependsOn "post-build" already caused it to run.  Since nx-semantic-release runs "build" regardless, it wipes out the post processing step.

If I specify the "buildTarget" as I have shown, can nx-semantic-release honor the dependsOn of post-build so that the build and post build targets all run correctly?

**Comment by TheUnderScorer** [comment]
Hey @tet-lenovo.

We use the `runExecutor` function from `@nx/devkit` so in theory it should be honored 😁. I'll take a look at it when I will have some more spare time.
